#!/bin/bash
# Title:     	clearAuxFiles.sh
# Date:       	06/05/2021
# Author:      Shao Jie Hu Chen
# Version:     1.0
# Description: It clears all aux files generated by LaTeX.
# Options:    	No options
# Use:         ./clearAuxFiles.sh

rm ../*/*.{aux,log,gz}
